$axure.loadCurrentPage({
  "url":"融资过程介绍.html",
  "generationDate":new Date(1428854865375.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c681238d07ac4f9fb8c750125cba3aad",
    "type":"Axure:Page",
    "name":"融资过程介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c80391b6ae34c40af6213c3aa6321f8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb3cc1f9cc5c4979a69fe00a90f78085"},
{
          "id":"129a2e85126444c190b3ae5e118c3d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":120},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"316050a9613a46489af48fd1cf77bffb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":120},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 我要融资",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"b10e3527b4e54a20805c788bcdeab08a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":170},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u28_line.png"}},
{
          "id":"fe60e6c5c71245be99eeacd57b42171b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":196},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f0bd9fec5948cf8de616be04b1be8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":196},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 选择融资类型",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"6ca1ac1610454e00a9091663e6e5363f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":270},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d6e06350c049d891601373e161f72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":270},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 种子基金",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"b2f74617b125431ba7c74de2373a9f27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":270},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25215b709a3848fb818d5183366699fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":270},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 投资人融资",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"8d15bd97899c487eaaa6a1e7aac0ba7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":340},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98768d0323224449be493a05fd7d122a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":340},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 申请线上路演",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":5,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"227e84b4e4ff4b00b1867666eb880bea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":480},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56817df9b0e549d0a6e98b963177dcce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":480},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 参与线下路演",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":8,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"e9e66e38806241539842f6f505cca1e0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":390},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u39_line.png"}},
{
          "id":"c9d12e4ff3174098a2e4ba281e177d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF008CCF},
            "location":{
              "x":440,
              "y":340},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32bca82bdcfb4db5a6cb8d40fef061c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF008CCF},
                "location":{
                  "x":440,
                  "y":340},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 投资人直接联系",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":7,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/融资过程介绍/u40.png"}},
{
          "id":"eab8b606c7834b33a71726d4ac4a3ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF008CCF},
            "location":{
              "x":200,
              "y":410},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55ce1e6bebc447b2a72eeec4a0278340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF008CCF},
                "location":{
                  "x":200,
                  "y":410},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 投资人邀请线下路演",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":6,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/融资过程介绍/u40.png"}},
{
          "id":"7e68d79a438a42a09952904c5ee14107",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":460},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u39_line.png"}},
{
          "id":"bc8a7a8b026f42649035f3b8b1f0eaa1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":246},
            "size":{
              "width":10,
              "height":24}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u45_line.png"}},
{
          "id":"d96a9b57c4044c489ce6a3019835b05b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":246},
            "size":{
              "width":10,
              "height":24}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u45_line.png"}},
{
          "id":"71f27aeb811347e59942a1b22f083af4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":320},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u39_line.png"}},
{
          "id":"1a8684ccb607425e96d95a2c89930d6d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":320},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u39_line.png"}},
{
          "id":"edac9a5c199544daa6a1bfbc02ebdb66",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":530},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u49_line.png"}},
{
          "id":"faf5e9eb10d04b318c2f58f15d3787fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":780},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3e481330074b89aa7ec8e0a52236df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":780},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 融资登记",
                      "target":{
                        "targetType":"page",
                        "url":"融资登记.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册页/u60.png"}},
{
          "id":"849d8d1e03944d34b680a35548558117",
          "label":"融资过程介绍",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":120},
            "size":{
              "width":640,
              "height":570}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"67dc91d28738474db059fdbc16182950",
              "label":"我要融资",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"02f7ff7beedd4139baf2fb08719a09dc",
              "label":"选择融资类型",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"43a618838d3f4383a3cefaef4f0dd452",
              "label":"种子基金",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"3c28240edd2146ccaa5a8125685234b1",
              "label":"投资人融资",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"5d703a412d35401fb047cea9f8d6ff3c",
              "label":"申请线上路演",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"3b09f1da5b7a4d548a1809407710fff2",
              "label":"投资人邀请线下路演",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"126684702d7b4b5eae2e50e4f6a3de92",
              "label":"投资人直接联系",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"949b2cf0aa4c42b780e2fc207274b936",
              "label":"参与线下路演",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"305c0b8301b345ed8cf798433c2ea9f2",
              "label":"路演结果反馈",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"517eb2134d7e4b74ac5624384d2cb369",
              "label":"再次融资",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"c9e5546fb29c48338c3bfef40daa9720",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":930}},
          "adaptiveStyles":{
},
          "masterId":"70ecf6840e174f1ba5ed45a740d3b1b9"},
{
          "id":"a7bf31591dd043d6b87d066090e2a4a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":560},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d2acc5f8e04beb89154a8b059a724e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":560},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 路演结果反馈",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":9,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"6e71b0053a0f4065b859a98bc78d6ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":640},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f989a1774861440aadf3252f76738df8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":640},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 融资过程介绍 to 再次融资",
                      "panelsToStates":[{
                          "panelPath":["849d8d1e03944d34b680a35548558117"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":10,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "images":{
            "normal~":"images/注册页/u71.png"}},
{
          "id":"0842e9d2e6e443c7b10157460a93a080",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":610},
            "size":{
              "width":10,
              "height":30}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u49_line.png"}},
{
          "id":"b7bcd9c31afb424082e5c50a6791b708",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":360},
            "size":{
              "width":40,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/融资过程介绍/u92_line.png"}}]}},
  "masters":{
    "bb3cc1f9cc5c4979a69fe00a90f78085":{
      "packageId":"bb3cc1f9cc5c4979a69fe00a90f78085",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd2df894b45c4e379f35e08d5b614054",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1371AE},
              "size":{
                "width":1347,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9f668b67bcb4f3a96811e5327cc55b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1371AE},
                  "size":{
                    "width":1347,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u260.png"}},
{
            "id":"5b742cc4596646bf99fca4537acdcb57",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":70,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b5e49fae6b6e4dfd87dfa817ba65d468",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":70,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u262.jpg"}},
{
            "id":"1fde09a019704bfcbf25ddcb7563e576",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":100,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13005ff44f374dfcbc824dbe6c171e21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 Home",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e422d49570b44cfb27df77131e605ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":170,
                "y":21},
              "size":{
                "width":100,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b01253aa4f6f42ab8f1f7258f3c00ceb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":170,
                    "y":21},
                  "size":{
                    "width":100,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 正在融资",
                        "target":{
                          "targetType":"page",
                          "url":"正在融资.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ef1b474b0b54429597e6e24231f603cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":293,
                "y":21},
              "size":{
                "width":73,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2e59a1c474944aa3e9f08dfdaa43b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":293,
                    "y":21},
                  "size":{
                    "width":73,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da23cf4ea68e4b13a1ce2efa46e0f900",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":783,
                "y":20},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fe7c027da924e5eaa58a7363af19273",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":783,
                    "y":20},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"92229a63fff24dd3ba904dbf342ff54f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":1020,
                "y":21},
              "size":{
                "width":230,
                "height":28}},
            "adaptiveStyles":{
}},
{
            "id":"ecab33d6a3f649a084534f2b6129ed59",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":913,
                "y":18},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31eb8fa6cd18477a86ca228e4df829c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":913,
                    "y":18},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a9b4273753446ae86373583f272f18f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":661,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1a4d85061764ac097787de029a2f210",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":661,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 注册页",
                        "target":{
                          "targetType":"page",
                          "url":"注册页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d759cfbc13004e33bcc1b58a394a4fa5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":720,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d44bc16a54646c38a61f88ea55c3cf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":720,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23cdc19380e14901a3d10a9160e2da50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":602,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3de6b9102ae4158937c72e33e915055",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":602,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 管理",
                        "target":{
                          "targetType":"page",
                          "url":"管理.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88fe3309936c4523972ca211b1cfa456",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1260,
                "y":21},
              "size":{
                "width":60,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0cf294ca8c84d3daa52b26add15a772",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1260,
                    "y":21},
                  "size":{
                    "width":60,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u281.png"}},
{
            "id":"39218ba529ae473a9eb2e10c1844aa65",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":390,
                "y":21},
              "size":{
                "width":103,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0ff4d3aa6a7499e96e0d07c3b834115",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":21},
                  "size":{
                    "width":103,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "70ecf6840e174f1ba5ed45a740d3b1b9":{
      "packageId":"70ecf6840e174f1ba5ed45a740d3b1b9",
      "type":"Axure:Master",
      "name":"bottom",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"870dc619b7624a7bb783758f3e6bcd4c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-91,
                "y":97.5},
              "size":{
                "width":1060,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u52_line.png"}},
{
            "id":"a6e193a87c9d4f9195b6f661c0b52840",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":268.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3547c6d0057241b89e44c854c7c2eca3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":268.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"667820f597ef4e0abf8570b20c866830",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":238,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d7356c9b724809b3af215af0dd059f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":238,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 隐私条款",
                        "target":{
                          "targetType":"page",
                          "url":"隐私条款.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4180d91bb6064e3f87560e5870f1dafc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":446,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"000c88dfb4b948d5bbf4cbe2e8b1909e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":446,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户反馈",
                        "target":{
                          "targetType":"page",
                          "url":"用户反馈.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"760d9d7785044c1295470b90c6a958c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":654,
                "y":290},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"be89e24431f04a1282f2e9141f45781e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":654,
                    "y":290},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d43eda697b704de1bc0e36c7f398d8be",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":134,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18965694c5f4461195ea9458b4d829f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":134,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4286e00408be47da99e534eda7881137",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":364.5,
                "y":230},
              "size":{
                "width":74,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d879fd40860b40298b7746dca7a6d674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":364.5,
                    "y":230},
                  "size":{
                    "width":74,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5408cd0d4a4745b08a43b49508626916",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":448.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c6a8342a39d456e9e9991ff6c3b2c28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":448.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1947b3844d8c4c4f8f32d19f58b1195f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":534.5,
                "y":230},
              "size":{
                "width":75,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef6d6109bc204e50bfb5b852672f4561",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":534.5,
                    "y":230},
                  "size":{
                    "width":75,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2038dfac4b9947f68ee022a21392f3c2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":280,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19c3e87af52c4e54af20881dc99afe8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":280,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"c3c0b06791e5491a9f22fc47f76da691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":364,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"708a2a31f49e46febde87f114eadab48",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":364,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5a5d0df23a354b1ba2fb6883515a2945",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":450,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f7a6c9306d94dc287dffad228e53e1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":450,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"803048c9993a474495d8f229da259ae1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":546.5,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a1ccd5ff2ea476ab0083c66675a8ad0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":546.5,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5cda459e85a14a02a33863959d2fc476",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":342,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9f6be80841146cdb7e4d06fb833b0a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":342,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 社区规范",
                        "target":{
                          "targetType":"page",
                          "url":"社区规范.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"912acfaaa26a40939c9f67b9de6f4e1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":550,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e0388dfda8d4ddf99579afecffe97b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":550,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d65728ec7c846e085d905c737049f0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":344},
              "size":{
                "width":422,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfb4c458f9b2475e806c1f35dae27f3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":309,
                    "y":344},
                  "size":{
                    "width":422,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79ee184e62534d3b96322c07ad04aab1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":334,
                "y":400},
              "size":{
                "width":200,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf932e7eeef24ae98fc448da2d1ab0ee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":334,
                    "y":400},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u83.png"}}]}}},
  "objectPaths":{
    "1c80391b6ae34c40af6213c3aa6321f8":{
      "scriptId":"u0",
      "fd2df894b45c4e379f35e08d5b614054":{
        "scriptId":"u1"},
      "c9f668b67bcb4f3a96811e5327cc55b8":{
        "scriptId":"u2"},
      "5b742cc4596646bf99fca4537acdcb57":{
        "scriptId":"u3"},
      "b5e49fae6b6e4dfd87dfa817ba65d468":{
        "scriptId":"u4"},
      "1fde09a019704bfcbf25ddcb7563e576":{
        "scriptId":"u5"},
      "13005ff44f374dfcbc824dbe6c171e21":{
        "scriptId":"u6"},
      "2e422d49570b44cfb27df77131e605ec":{
        "scriptId":"u7"},
      "b01253aa4f6f42ab8f1f7258f3c00ceb":{
        "scriptId":"u8"},
      "ef1b474b0b54429597e6e24231f603cd":{
        "scriptId":"u9"},
      "cdf2e59a1c474944aa3e9f08dfdaa43b":{
        "scriptId":"u10"},
      "da23cf4ea68e4b13a1ce2efa46e0f900":{
        "scriptId":"u11"},
      "3fe7c027da924e5eaa58a7363af19273":{
        "scriptId":"u12"},
      "92229a63fff24dd3ba904dbf342ff54f":{
        "scriptId":"u13"},
      "ecab33d6a3f649a084534f2b6129ed59":{
        "scriptId":"u14"},
      "31eb8fa6cd18477a86ca228e4df829c8":{
        "scriptId":"u15"},
      "2a9b4273753446ae86373583f272f18f":{
        "scriptId":"u16"},
      "e1a4d85061764ac097787de029a2f210":{
        "scriptId":"u17"},
      "d759cfbc13004e33bcc1b58a394a4fa5":{
        "scriptId":"u18"},
      "8d44bc16a54646c38a61f88ea55c3cf3":{
        "scriptId":"u19"},
      "23cdc19380e14901a3d10a9160e2da50":{
        "scriptId":"u20"},
      "a3de6b9102ae4158937c72e33e915055":{
        "scriptId":"u21"},
      "88fe3309936c4523972ca211b1cfa456":{
        "scriptId":"u22"},
      "e0cf294ca8c84d3daa52b26add15a772":{
        "scriptId":"u23"},
      "39218ba529ae473a9eb2e10c1844aa65":{
        "scriptId":"u24"},
      "a0ff4d3aa6a7499e96e0d07c3b834115":{
        "scriptId":"u25"}},
    "129a2e85126444c190b3ae5e118c3d6e":{
      "scriptId":"u26"},
    "316050a9613a46489af48fd1cf77bffb":{
      "scriptId":"u27"},
    "b10e3527b4e54a20805c788bcdeab08a":{
      "scriptId":"u28"},
    "fe60e6c5c71245be99eeacd57b42171b":{
      "scriptId":"u29"},
    "39f0bd9fec5948cf8de616be04b1be8b":{
      "scriptId":"u30"},
    "6ca1ac1610454e00a9091663e6e5363f":{
      "scriptId":"u31"},
    "17d6e06350c049d891601373e161f72d":{
      "scriptId":"u32"},
    "b2f74617b125431ba7c74de2373a9f27":{
      "scriptId":"u33"},
    "25215b709a3848fb818d5183366699fd":{
      "scriptId":"u34"},
    "8d15bd97899c487eaaa6a1e7aac0ba7f":{
      "scriptId":"u35"},
    "98768d0323224449be493a05fd7d122a":{
      "scriptId":"u36"},
    "227e84b4e4ff4b00b1867666eb880bea":{
      "scriptId":"u37"},
    "56817df9b0e549d0a6e98b963177dcce":{
      "scriptId":"u38"},
    "e9e66e38806241539842f6f505cca1e0":{
      "scriptId":"u39"},
    "c9d12e4ff3174098a2e4ba281e177d8f":{
      "scriptId":"u40"},
    "32bca82bdcfb4db5a6cb8d40fef061c1":{
      "scriptId":"u41"},
    "eab8b606c7834b33a71726d4ac4a3ff6":{
      "scriptId":"u42"},
    "55ce1e6bebc447b2a72eeec4a0278340":{
      "scriptId":"u43"},
    "7e68d79a438a42a09952904c5ee14107":{
      "scriptId":"u44"},
    "bc8a7a8b026f42649035f3b8b1f0eaa1":{
      "scriptId":"u45"},
    "d96a9b57c4044c489ce6a3019835b05b":{
      "scriptId":"u46"},
    "71f27aeb811347e59942a1b22f083af4":{
      "scriptId":"u47"},
    "1a8684ccb607425e96d95a2c89930d6d":{
      "scriptId":"u48"},
    "edac9a5c199544daa6a1bfbc02ebdb66":{
      "scriptId":"u49"},
    "faf5e9eb10d04b318c2f58f15d3787fb":{
      "scriptId":"u50"},
    "4f3e481330074b89aa7ec8e0a52236df":{
      "scriptId":"u51"},
    "849d8d1e03944d34b680a35548558117":{
      "scriptId":"u52"},
    "c9e5546fb29c48338c3bfef40daa9720":{
      "scriptId":"u53",
      "870dc619b7624a7bb783758f3e6bcd4c":{
        "scriptId":"u54"},
      "a6e193a87c9d4f9195b6f661c0b52840":{
        "scriptId":"u55"},
      "3547c6d0057241b89e44c854c7c2eca3":{
        "scriptId":"u56"},
      "667820f597ef4e0abf8570b20c866830":{
        "scriptId":"u57"},
      "82d7356c9b724809b3af215af0dd059f":{
        "scriptId":"u58"},
      "4180d91bb6064e3f87560e5870f1dafc":{
        "scriptId":"u59"},
      "000c88dfb4b948d5bbf4cbe2e8b1909e":{
        "scriptId":"u60"},
      "760d9d7785044c1295470b90c6a958c1":{
        "scriptId":"u61"},
      "be89e24431f04a1282f2e9141f45781e":{
        "scriptId":"u62"},
      "d43eda697b704de1bc0e36c7f398d8be":{
        "scriptId":"u63"},
      "18965694c5f4461195ea9458b4d829f8":{
        "scriptId":"u64"},
      "4286e00408be47da99e534eda7881137":{
        "scriptId":"u65"},
      "d879fd40860b40298b7746dca7a6d674":{
        "scriptId":"u66"},
      "5408cd0d4a4745b08a43b49508626916":{
        "scriptId":"u67"},
      "6c6a8342a39d456e9e9991ff6c3b2c28":{
        "scriptId":"u68"},
      "1947b3844d8c4c4f8f32d19f58b1195f":{
        "scriptId":"u69"},
      "ef6d6109bc204e50bfb5b852672f4561":{
        "scriptId":"u70"},
      "2038dfac4b9947f68ee022a21392f3c2":{
        "scriptId":"u71"},
      "19c3e87af52c4e54af20881dc99afe8d":{
        "scriptId":"u72"},
      "c3c0b06791e5491a9f22fc47f76da691":{
        "scriptId":"u73"},
      "708a2a31f49e46febde87f114eadab48":{
        "scriptId":"u74"},
      "5a5d0df23a354b1ba2fb6883515a2945":{
        "scriptId":"u75"},
      "5f7a6c9306d94dc287dffad228e53e1d":{
        "scriptId":"u76"},
      "803048c9993a474495d8f229da259ae1":{
        "scriptId":"u77"},
      "6a1ccd5ff2ea476ab0083c66675a8ad0":{
        "scriptId":"u78"},
      "5cda459e85a14a02a33863959d2fc476":{
        "scriptId":"u79"},
      "b9f6be80841146cdb7e4d06fb833b0a4":{
        "scriptId":"u80"},
      "912acfaaa26a40939c9f67b9de6f4e1a":{
        "scriptId":"u81"},
      "8e0388dfda8d4ddf99579afecffe97b4":{
        "scriptId":"u82"},
      "4d65728ec7c846e085d905c737049f0e":{
        "scriptId":"u83"},
      "cfb4c458f9b2475e806c1f35dae27f3b":{
        "scriptId":"u84"},
      "79ee184e62534d3b96322c07ad04aab1":{
        "scriptId":"u85"},
      "cf932e7eeef24ae98fc448da2d1ab0ee":{
        "scriptId":"u86"}},
    "a7bf31591dd043d6b87d066090e2a4a5":{
      "scriptId":"u87"},
    "d4d2acc5f8e04beb89154a8b059a724e":{
      "scriptId":"u88"},
    "6e71b0053a0f4065b859a98bc78d6ad1":{
      "scriptId":"u89"},
    "f989a1774861440aadf3252f76738df8":{
      "scriptId":"u90"},
    "0842e9d2e6e443c7b10157460a93a080":{
      "scriptId":"u91"},
    "b7bcd9c31afb424082e5c50a6791b708":{
      "scriptId":"u92"}}});