$axure.loadCurrentPage({
  "url":"编辑项目路演页.html",
  "generationDate":new Date(1422972161914.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"668850378bf3463e92d59c5a9369cb6d",
    "type":"Axure:Page",
    "name":"编辑项目路演页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1f9dff28023f4021aa434308d9741df6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb3cc1f9cc5c4979a69fe00a90f78085"},
{
          "id":"aece25d46864422bb8680c2c2ef64a7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":238},
            "size":{
              "width":410,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb86b0f7dcf4875a4ef3169817629b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":238},
                "size":{
                  "width":410,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑项目路演页/u24.png"}},
{
          "id":"19677db5438d411f8d41d9afa89082f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":200},
            "size":{
              "width":250,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9954382958941fd8b94f8cf97410db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":200},
                "size":{
                  "width":250,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66ef5457e32f4c10b5c1437b72dac355",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":238},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62bf030f4aff4c3cb3b0e4a9e50566d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":238},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}},
{
          "id":"1c12133622064384bb0b4150db5eaebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":498},
            "size":{
              "width":250,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35de28f3ab7a48ff9eb1f235260168eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":498},
                "size":{
                  "width":250,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1220d0fe99534e5cb2d9076f260211c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":536},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50affc25ccd4b64b5406a5c55d2b71b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":536},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}},
{
          "id":"95312ab4493546409c097906ecad7be1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":536},
            "size":{
              "width":410,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0916f21fd014bc192fb247a0c9b31c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":536},
                "size":{
                  "width":410,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑项目路演页/u24.png"}},
{
          "id":"ffa77be730ee42adaebc0c331a9333ff",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":734},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e5da95cd9af402ea532216e423ae20a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":734},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a045a665f01c4c9b8374ec118c4aaf73",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":760},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655b046c35d340bd94f49cd7cae601e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":760},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b6397d285f2345ebbecbb26a3245d7ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":798},
            "size":{
              "width":410,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49f2d235104d4453b312ee26d2b0e585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":798},
                "size":{
                  "width":410,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑项目路演页/u24.png"}},
{
          "id":"f57b7506d74a49c6abd24aff7ca6406f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":996},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e913a1d015064eadaa5c51ce439562a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":996},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bbc98bb9289143fdbbf4046e3e75fabe",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":1022},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ed3b3656314d2dbaacec3c53703e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":1022},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"62f64b8b947840d798415f82a43f52b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":1068},
            "size":{
              "width":410,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53629213c3b04b7aaa505309d35db276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":1068},
                "size":{
                  "width":410,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑项目路演页/u24.png"}},
{
          "id":"9a21be17e3d2416da3252a8c10af05ca",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":1266},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55e3886096d44c6a96532ab946c7bde9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":1266},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"13608b4d93bb4fc082d7a301a9e7a4d9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":1292},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f98c0a51b64471d8b01da30dc7c176f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":1292},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d2e529aeb67e432c946c4c1ef7d571bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":90},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3628f851093f44d09f485cd0e0842bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":90},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}},
{
          "id":"a04a6f24ac3342f6935a77ea3ab274c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":90},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffaf75ef81b64f4f845f7219d063bd67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":90},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}}]}},
  "masters":{
    "bb3cc1f9cc5c4979a69fe00a90f78085":{
      "packageId":"bb3cc1f9cc5c4979a69fe00a90f78085",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd2df894b45c4e379f35e08d5b614054",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1371AE},
              "size":{
                "width":1347,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9f668b67bcb4f3a96811e5327cc55b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1371AE},
                  "size":{
                    "width":1347,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u258.png"}},
{
            "id":"5b742cc4596646bf99fca4537acdcb57",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":70,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b5e49fae6b6e4dfd87dfa817ba65d468",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":70,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u260.jpg"}},
{
            "id":"1fde09a019704bfcbf25ddcb7563e576",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":100,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13005ff44f374dfcbc824dbe6c171e21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 Home",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e422d49570b44cfb27df77131e605ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":170,
                "y":21},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b01253aa4f6f42ab8f1f7258f3c00ceb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":170,
                    "y":21},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 正在融资",
                        "target":{
                          "targetType":"page",
                          "url":"正在融资.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ef1b474b0b54429597e6e24231f603cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":293,
                "y":21},
              "size":{
                "width":73,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2e59a1c474944aa3e9f08dfdaa43b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":293,
                    "y":21},
                  "size":{
                    "width":73,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da23cf4ea68e4b13a1ce2efa46e0f900",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":783,
                "y":20},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fe7c027da924e5eaa58a7363af19273",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":783,
                    "y":20},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"92229a63fff24dd3ba904dbf342ff54f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":1020,
                "y":21},
              "size":{
                "width":230,
                "height":28}},
            "adaptiveStyles":{
}},
{
            "id":"ecab33d6a3f649a084534f2b6129ed59",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":913,
                "y":18},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31eb8fa6cd18477a86ca228e4df829c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":913,
                    "y":18},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a9b4273753446ae86373583f272f18f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":661,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1a4d85061764ac097787de029a2f210",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":661,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 注册页",
                        "target":{
                          "targetType":"page",
                          "url":"注册页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d759cfbc13004e33bcc1b58a394a4fa5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":720,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d44bc16a54646c38a61f88ea55c3cf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":720,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23cdc19380e14901a3d10a9160e2da50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":602,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3de6b9102ae4158937c72e33e915055",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":602,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 管理",
                        "target":{
                          "targetType":"page",
                          "url":"管理.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88fe3309936c4523972ca211b1cfa456",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1260,
                "y":21},
              "size":{
                "width":60,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0cf294ca8c84d3daa52b26add15a772",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1260,
                    "y":21},
                  "size":{
                    "width":60,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u279.png"}}]}}},
  "objectPaths":{
    "1f9dff28023f4021aa434308d9741df6":{
      "scriptId":"u0",
      "fd2df894b45c4e379f35e08d5b614054":{
        "scriptId":"u1"},
      "c9f668b67bcb4f3a96811e5327cc55b8":{
        "scriptId":"u2"},
      "5b742cc4596646bf99fca4537acdcb57":{
        "scriptId":"u3"},
      "b5e49fae6b6e4dfd87dfa817ba65d468":{
        "scriptId":"u4"},
      "1fde09a019704bfcbf25ddcb7563e576":{
        "scriptId":"u5"},
      "13005ff44f374dfcbc824dbe6c171e21":{
        "scriptId":"u6"},
      "2e422d49570b44cfb27df77131e605ec":{
        "scriptId":"u7"},
      "b01253aa4f6f42ab8f1f7258f3c00ceb":{
        "scriptId":"u8"},
      "ef1b474b0b54429597e6e24231f603cd":{
        "scriptId":"u9"},
      "cdf2e59a1c474944aa3e9f08dfdaa43b":{
        "scriptId":"u10"},
      "da23cf4ea68e4b13a1ce2efa46e0f900":{
        "scriptId":"u11"},
      "3fe7c027da924e5eaa58a7363af19273":{
        "scriptId":"u12"},
      "92229a63fff24dd3ba904dbf342ff54f":{
        "scriptId":"u13"},
      "ecab33d6a3f649a084534f2b6129ed59":{
        "scriptId":"u14"},
      "31eb8fa6cd18477a86ca228e4df829c8":{
        "scriptId":"u15"},
      "2a9b4273753446ae86373583f272f18f":{
        "scriptId":"u16"},
      "e1a4d85061764ac097787de029a2f210":{
        "scriptId":"u17"},
      "d759cfbc13004e33bcc1b58a394a4fa5":{
        "scriptId":"u18"},
      "8d44bc16a54646c38a61f88ea55c3cf3":{
        "scriptId":"u19"},
      "23cdc19380e14901a3d10a9160e2da50":{
        "scriptId":"u20"},
      "a3de6b9102ae4158937c72e33e915055":{
        "scriptId":"u21"},
      "88fe3309936c4523972ca211b1cfa456":{
        "scriptId":"u22"},
      "e0cf294ca8c84d3daa52b26add15a772":{
        "scriptId":"u23"}},
    "aece25d46864422bb8680c2c2ef64a7b":{
      "scriptId":"u24"},
    "aeb86b0f7dcf4875a4ef3169817629b2":{
      "scriptId":"u25"},
    "19677db5438d411f8d41d9afa89082f2":{
      "scriptId":"u26"},
    "d9954382958941fd8b94f8cf97410db5":{
      "scriptId":"u27"},
    "66ef5457e32f4c10b5c1437b72dac355":{
      "scriptId":"u28"},
    "62bf030f4aff4c3cb3b0e4a9e50566d2":{
      "scriptId":"u29"},
    "1c12133622064384bb0b4150db5eaebf":{
      "scriptId":"u30"},
    "35de28f3ab7a48ff9eb1f235260168eb":{
      "scriptId":"u31"},
    "1220d0fe99534e5cb2d9076f260211c5":{
      "scriptId":"u32"},
    "a50affc25ccd4b64b5406a5c55d2b71b":{
      "scriptId":"u33"},
    "95312ab4493546409c097906ecad7be1":{
      "scriptId":"u34"},
    "e0916f21fd014bc192fb247a0c9b31c9":{
      "scriptId":"u35"},
    "ffa77be730ee42adaebc0c331a9333ff":{
      "scriptId":"u36"},
    "2e5da95cd9af402ea532216e423ae20a":{
      "scriptId":"u37"},
    "a045a665f01c4c9b8374ec118c4aaf73":{
      "scriptId":"u38"},
    "655b046c35d340bd94f49cd7cae601e7":{
      "scriptId":"u39"},
    "b6397d285f2345ebbecbb26a3245d7ef":{
      "scriptId":"u40"},
    "49f2d235104d4453b312ee26d2b0e585":{
      "scriptId":"u41"},
    "f57b7506d74a49c6abd24aff7ca6406f":{
      "scriptId":"u42"},
    "e913a1d015064eadaa5c51ce439562a5":{
      "scriptId":"u43"},
    "bbc98bb9289143fdbbf4046e3e75fabe":{
      "scriptId":"u44"},
    "49ed3b3656314d2dbaacec3c53703e8a":{
      "scriptId":"u45"},
    "62f64b8b947840d798415f82a43f52b1":{
      "scriptId":"u46"},
    "53629213c3b04b7aaa505309d35db276":{
      "scriptId":"u47"},
    "9a21be17e3d2416da3252a8c10af05ca":{
      "scriptId":"u48"},
    "55e3886096d44c6a96532ab946c7bde9":{
      "scriptId":"u49"},
    "13608b4d93bb4fc082d7a301a9e7a4d9":{
      "scriptId":"u50"},
    "5f98c0a51b64471d8b01da30dc7c176f":{
      "scriptId":"u51"},
    "d2e529aeb67e432c946c4c1ef7d571bb":{
      "scriptId":"u52"},
    "3628f851093f44d09f485cd0e0842bbe":{
      "scriptId":"u53"},
    "a04a6f24ac3342f6935a77ea3ab274c8":{
      "scriptId":"u54"},
    "ffaf75ef81b64f4f845f7219d063bd67":{
      "scriptId":"u55"}}});