$axure.loadCurrentPage({
  "url":"项目创建审核与管理.html",
  "generationDate":new Date(1428854872761.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6a2931e595e44c9a65f4323b8c2c967",
    "type":"Axure:Page",
    "name":"项目创建审核与管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d165432bf1f24039a94997e6479d4ded",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb3cc1f9cc5c4979a69fe00a90f78085"},
{
          "id":"3dad1ed28c2347fa8cc499c956b7b276",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":210,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d1ef4e08674188bbd6c9871e219ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":110},
                "size":{
                  "width":210,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目审核 to 待审核",
                      "panelsToStates":[{
                          "panelPath":["05a7a4aeddbd4346b343437f3abb4a05"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/项目创建审核与管理/u26.png"}},
{
          "id":"68d0e0c7a53347afa144f6cc3a8e796b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":210,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19db17e427824fae9ea06205a2fd92f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":210,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目审核 to 已审核",
                      "panelsToStates":[{
                          "panelPath":["05a7a4aeddbd4346b343437f3abb4a05"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/项目创建审核与管理/u26.png"}},
{
          "id":"8c1b7f72dcf545b2953382dc90b36eeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":210,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a4335db23a4bcb9a9bcdeee3cd63e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":210,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目审核 to 超过6个月未更新",
                      "panelsToStates":[{
                          "panelPath":["05a7a4aeddbd4346b343437f3abb4a05"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/项目创建审核与管理/u26.png"}},
{
          "id":"05a7a4aeddbd4346b343437f3abb4a05",
          "label":"项目审核",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":110},
            "size":{
              "width":1127,
              "height":390}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1236072b12fd4fb9923bc45b3fbd8d2a",
              "label":"待审核",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aed8aa66651f44bf86062d1f08cc69da",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":39}},
                  "adaptiveStyles":{
},
                  "masterId":"85b01447e49a40d2b34b56f5a4f05bc3"},
{
                  "id":"4899f3319b354935acf63897625e5f87",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":720,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd2471a1219a4877b5fd1c391fd4b672",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":720,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}},
{
                  "id":"64fdcf781d83403d9462d05d22474351",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":913,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbee86081f2c4f6190d73e7fdfb82db9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":913,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}}]},
{
              "id":"8fda53e637124128ab978c2e33c4d09a",
              "label":"已审核",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3c49597d2afb41118b558597e91537df",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":39}},
                  "adaptiveStyles":{
},
                  "masterId":"85b01447e49a40d2b34b56f5a4f05bc3"},
{
                  "id":"a4a8753de5e042c09c0a0fdcce6b53e8",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":720,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87eb3b659deb40308c4c754504da0b5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":720,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}},
{
                  "id":"9e0ae18402384ffe916d452dbd1fd5ae",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":913,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfa8c73c55d24a61979e18f1c1b803d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":913,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}}]},
{
              "id":"595d122702494c1c8b0293f2de56be60",
              "label":"超过6个月未更新",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0d2976e8560d43eb916959d16c9e68ea",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":39}},
                  "adaptiveStyles":{
},
                  "masterId":"85b01447e49a40d2b34b56f5a4f05bc3"},
{
                  "id":"eb2e03133e6f408280f7b730c8972231",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":720,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fbf0f0b60644dc28b62ee757c9b1431",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":720,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}},
{
                  "id":"cc97ad3307fe48b1ae6ba452b772971d",
                  "label":"",
                  "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":913,
                      "y":40},
                    "size":{
                      "width":160,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c034ff7fcdc423ebf36d8f548d9439c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05a7a4aeddbd4346b343437f3abb4a05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":913,
                          "y":40},
                        "size":{
                          "width":160,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目创建审核与管理/u46.png"}}]}]},
{
          "id":"c9421bd4250245e58c4e7ac66369235f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":528}},
          "adaptiveStyles":{
},
          "masterId":"70ecf6840e174f1ba5ed45a740d3b1b9"}]}},
  "masters":{
    "bb3cc1f9cc5c4979a69fe00a90f78085":{
      "packageId":"bb3cc1f9cc5c4979a69fe00a90f78085",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd2df894b45c4e379f35e08d5b614054",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1371AE},
              "size":{
                "width":1347,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9f668b67bcb4f3a96811e5327cc55b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1371AE},
                  "size":{
                    "width":1347,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u260.png"}},
{
            "id":"5b742cc4596646bf99fca4537acdcb57",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":70,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b5e49fae6b6e4dfd87dfa817ba65d468",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":70,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u262.jpg"}},
{
            "id":"1fde09a019704bfcbf25ddcb7563e576",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":100,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13005ff44f374dfcbc824dbe6c171e21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 Home",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e422d49570b44cfb27df77131e605ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":170,
                "y":21},
              "size":{
                "width":100,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b01253aa4f6f42ab8f1f7258f3c00ceb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":170,
                    "y":21},
                  "size":{
                    "width":100,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 正在融资",
                        "target":{
                          "targetType":"page",
                          "url":"正在融资.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ef1b474b0b54429597e6e24231f603cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":293,
                "y":21},
              "size":{
                "width":73,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2e59a1c474944aa3e9f08dfdaa43b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":293,
                    "y":21},
                  "size":{
                    "width":73,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da23cf4ea68e4b13a1ce2efa46e0f900",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":783,
                "y":20},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fe7c027da924e5eaa58a7363af19273",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":783,
                    "y":20},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"92229a63fff24dd3ba904dbf342ff54f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":1020,
                "y":21},
              "size":{
                "width":230,
                "height":28}},
            "adaptiveStyles":{
}},
{
            "id":"ecab33d6a3f649a084534f2b6129ed59",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":913,
                "y":18},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31eb8fa6cd18477a86ca228e4df829c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":913,
                    "y":18},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a9b4273753446ae86373583f272f18f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":661,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1a4d85061764ac097787de029a2f210",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":661,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 注册页",
                        "target":{
                          "targetType":"page",
                          "url":"注册页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d759cfbc13004e33bcc1b58a394a4fa5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":720,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d44bc16a54646c38a61f88ea55c3cf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":720,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23cdc19380e14901a3d10a9160e2da50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":602,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3de6b9102ae4158937c72e33e915055",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":602,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 管理",
                        "target":{
                          "targetType":"page",
                          "url":"管理.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88fe3309936c4523972ca211b1cfa456",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1260,
                "y":21},
              "size":{
                "width":60,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0cf294ca8c84d3daa52b26add15a772",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1260,
                    "y":21},
                  "size":{
                    "width":60,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u281.png"}},
{
            "id":"39218ba529ae473a9eb2e10c1844aa65",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":390,
                "y":21},
              "size":{
                "width":103,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0ff4d3aa6a7499e96e0d07c3b834115",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":21},
                  "size":{
                    "width":103,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "85b01447e49a40d2b34b56f5a4f05bc3":{
      "packageId":"85b01447e49a40d2b34b56f5a4f05bc3",
      "type":"Axure:Master",
      "name":"文本项目",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3d7e626b3ec44990ba4e13be5a550bbc",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":40,
                "y":40},
              "size":{
                "width":250,
                "height":250}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7faabc3d868940feae97ce8b702415e0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":40,
                    "y":40},
                  "size":{
                    "width":250,
                    "height":250}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目展示",
                        "target":{
                          "targetType":"page",
                          "url":"项目展示.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u170.png",
              "normal~":"images/home/u170.png",
              "normal~":"images/home/u170.png"}},
{
            "id":"b9a5dd6da1774fc38a08c66f8d477197",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "location":{
                "x":323,
                "y":171},
              "size":{
                "width":730,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ee1309b659824566b1175e8f2021d911",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "location":{
                    "x":323,
                    "y":171},
                  "size":{
                    "width":730,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ec5825be9ce94b00aef0b6c4ab7d3eb2",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":162},
              "size":{
                "width":730,
                "height":10},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u174_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u174_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u174_line.png"}},
{
            "id":"903c53c4055644d7b16376f47339cedc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"28px",
              "location":{
                "x":323,
                "y":40},
              "size":{
                "width":280,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8733d169521e47b7b01b8298c83e77bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"28px",
                  "location":{
                    "x":323,
                    "y":40},
                  "size":{
                    "width":280,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目展示",
                        "target":{
                          "targetType":"page",
                          "url":"项目展示.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"57e0cd83185a442c9bfcfd46ac6e7a17",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "location":{
                "x":323,
                "y":112},
              "size":{
                "width":280,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5e922e0a20524484a9eee585e46c55bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "location":{
                    "x":323,
                    "y":112},
                  "size":{
                    "width":280,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d68fb64882b64a35b506d881c6f9bd34",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "location":{
                "x":323,
                "y":138},
              "size":{
                "width":280,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24b30cb7f3c8464fabf7fc7a720d9fde",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "location":{
                    "x":323,
                    "y":138},
                  "size":{
                    "width":280,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"032d0f3c18724141a5b0e0b3b9bcd0f1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":40},
              "size":{
                "width":10,
                "height":250},
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u181_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u181_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u181_line.png"}}]}},
    "70ecf6840e174f1ba5ed45a740d3b1b9":{
      "packageId":"70ecf6840e174f1ba5ed45a740d3b1b9",
      "type":"Axure:Master",
      "name":"bottom",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"870dc619b7624a7bb783758f3e6bcd4c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-91,
                "y":97.5},
              "size":{
                "width":1060,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u52_line.png"}},
{
            "id":"a6e193a87c9d4f9195b6f661c0b52840",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":268.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3547c6d0057241b89e44c854c7c2eca3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":268.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"667820f597ef4e0abf8570b20c866830",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":238,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d7356c9b724809b3af215af0dd059f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":238,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 隐私条款",
                        "target":{
                          "targetType":"page",
                          "url":"隐私条款.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4180d91bb6064e3f87560e5870f1dafc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":446,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"000c88dfb4b948d5bbf4cbe2e8b1909e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":446,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户反馈",
                        "target":{
                          "targetType":"page",
                          "url":"用户反馈.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"760d9d7785044c1295470b90c6a958c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":654,
                "y":290},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"be89e24431f04a1282f2e9141f45781e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":654,
                    "y":290},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d43eda697b704de1bc0e36c7f398d8be",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":134,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18965694c5f4461195ea9458b4d829f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":134,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4286e00408be47da99e534eda7881137",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":364.5,
                "y":230},
              "size":{
                "width":74,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d879fd40860b40298b7746dca7a6d674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":364.5,
                    "y":230},
                  "size":{
                    "width":74,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5408cd0d4a4745b08a43b49508626916",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":448.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c6a8342a39d456e9e9991ff6c3b2c28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":448.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1947b3844d8c4c4f8f32d19f58b1195f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":534.5,
                "y":230},
              "size":{
                "width":75,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef6d6109bc204e50bfb5b852672f4561",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":534.5,
                    "y":230},
                  "size":{
                    "width":75,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2038dfac4b9947f68ee022a21392f3c2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":280,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19c3e87af52c4e54af20881dc99afe8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":280,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"c3c0b06791e5491a9f22fc47f76da691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":364,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"708a2a31f49e46febde87f114eadab48",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":364,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5a5d0df23a354b1ba2fb6883515a2945",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":450,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f7a6c9306d94dc287dffad228e53e1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":450,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"803048c9993a474495d8f229da259ae1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":546.5,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a1ccd5ff2ea476ab0083c66675a8ad0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":546.5,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5cda459e85a14a02a33863959d2fc476",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":342,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9f6be80841146cdb7e4d06fb833b0a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":342,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 社区规范",
                        "target":{
                          "targetType":"page",
                          "url":"社区规范.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"912acfaaa26a40939c9f67b9de6f4e1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":550,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e0388dfda8d4ddf99579afecffe97b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":550,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d65728ec7c846e085d905c737049f0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":344},
              "size":{
                "width":422,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfb4c458f9b2475e806c1f35dae27f3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":309,
                    "y":344},
                  "size":{
                    "width":422,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79ee184e62534d3b96322c07ad04aab1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":334,
                "y":400},
              "size":{
                "width":200,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf932e7eeef24ae98fc448da2d1ab0ee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":334,
                    "y":400},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u83.png"}}]}}},
  "objectPaths":{
    "d165432bf1f24039a94997e6479d4ded":{
      "scriptId":"u0",
      "fd2df894b45c4e379f35e08d5b614054":{
        "scriptId":"u1"},
      "c9f668b67bcb4f3a96811e5327cc55b8":{
        "scriptId":"u2"},
      "5b742cc4596646bf99fca4537acdcb57":{
        "scriptId":"u3"},
      "b5e49fae6b6e4dfd87dfa817ba65d468":{
        "scriptId":"u4"},
      "1fde09a019704bfcbf25ddcb7563e576":{
        "scriptId":"u5"},
      "13005ff44f374dfcbc824dbe6c171e21":{
        "scriptId":"u6"},
      "2e422d49570b44cfb27df77131e605ec":{
        "scriptId":"u7"},
      "b01253aa4f6f42ab8f1f7258f3c00ceb":{
        "scriptId":"u8"},
      "ef1b474b0b54429597e6e24231f603cd":{
        "scriptId":"u9"},
      "cdf2e59a1c474944aa3e9f08dfdaa43b":{
        "scriptId":"u10"},
      "da23cf4ea68e4b13a1ce2efa46e0f900":{
        "scriptId":"u11"},
      "3fe7c027da924e5eaa58a7363af19273":{
        "scriptId":"u12"},
      "92229a63fff24dd3ba904dbf342ff54f":{
        "scriptId":"u13"},
      "ecab33d6a3f649a084534f2b6129ed59":{
        "scriptId":"u14"},
      "31eb8fa6cd18477a86ca228e4df829c8":{
        "scriptId":"u15"},
      "2a9b4273753446ae86373583f272f18f":{
        "scriptId":"u16"},
      "e1a4d85061764ac097787de029a2f210":{
        "scriptId":"u17"},
      "d759cfbc13004e33bcc1b58a394a4fa5":{
        "scriptId":"u18"},
      "8d44bc16a54646c38a61f88ea55c3cf3":{
        "scriptId":"u19"},
      "23cdc19380e14901a3d10a9160e2da50":{
        "scriptId":"u20"},
      "a3de6b9102ae4158937c72e33e915055":{
        "scriptId":"u21"},
      "88fe3309936c4523972ca211b1cfa456":{
        "scriptId":"u22"},
      "e0cf294ca8c84d3daa52b26add15a772":{
        "scriptId":"u23"},
      "39218ba529ae473a9eb2e10c1844aa65":{
        "scriptId":"u24"},
      "a0ff4d3aa6a7499e96e0d07c3b834115":{
        "scriptId":"u25"}},
    "3dad1ed28c2347fa8cc499c956b7b276":{
      "scriptId":"u26"},
    "11d1ef4e08674188bbd6c9871e219ff4":{
      "scriptId":"u27"},
    "68d0e0c7a53347afa144f6cc3a8e796b":{
      "scriptId":"u28"},
    "19db17e427824fae9ea06205a2fd92f9":{
      "scriptId":"u29"},
    "8c1b7f72dcf545b2953382dc90b36eeb":{
      "scriptId":"u30"},
    "f6a4335db23a4bcb9a9bcdeee3cd63e6":{
      "scriptId":"u31"},
    "05a7a4aeddbd4346b343437f3abb4a05":{
      "scriptId":"u32"},
    "aed8aa66651f44bf86062d1f08cc69da":{
      "scriptId":"u33",
      "3d7e626b3ec44990ba4e13be5a550bbc":{
        "scriptId":"u34"},
      "7faabc3d868940feae97ce8b702415e0":{
        "scriptId":"u35"},
      "b9a5dd6da1774fc38a08c66f8d477197":{
        "scriptId":"u36"},
      "ee1309b659824566b1175e8f2021d911":{
        "scriptId":"u37"},
      "ec5825be9ce94b00aef0b6c4ab7d3eb2":{
        "scriptId":"u38"},
      "903c53c4055644d7b16376f47339cedc":{
        "scriptId":"u39"},
      "8733d169521e47b7b01b8298c83e77bc":{
        "scriptId":"u40"},
      "57e0cd83185a442c9bfcfd46ac6e7a17":{
        "scriptId":"u41"},
      "5e922e0a20524484a9eee585e46c55bc":{
        "scriptId":"u42"},
      "d68fb64882b64a35b506d881c6f9bd34":{
        "scriptId":"u43"},
      "24b30cb7f3c8464fabf7fc7a720d9fde":{
        "scriptId":"u44"},
      "032d0f3c18724141a5b0e0b3b9bcd0f1":{
        "scriptId":"u45"}},
    "4899f3319b354935acf63897625e5f87":{
      "scriptId":"u46"},
    "dd2471a1219a4877b5fd1c391fd4b672":{
      "scriptId":"u47"},
    "64fdcf781d83403d9462d05d22474351":{
      "scriptId":"u48"},
    "bbee86081f2c4f6190d73e7fdfb82db9":{
      "scriptId":"u49"},
    "3c49597d2afb41118b558597e91537df":{
      "scriptId":"u50",
      "3d7e626b3ec44990ba4e13be5a550bbc":{
        "scriptId":"u51"},
      "7faabc3d868940feae97ce8b702415e0":{
        "scriptId":"u52"},
      "b9a5dd6da1774fc38a08c66f8d477197":{
        "scriptId":"u53"},
      "ee1309b659824566b1175e8f2021d911":{
        "scriptId":"u54"},
      "ec5825be9ce94b00aef0b6c4ab7d3eb2":{
        "scriptId":"u55"},
      "903c53c4055644d7b16376f47339cedc":{
        "scriptId":"u56"},
      "8733d169521e47b7b01b8298c83e77bc":{
        "scriptId":"u57"},
      "57e0cd83185a442c9bfcfd46ac6e7a17":{
        "scriptId":"u58"},
      "5e922e0a20524484a9eee585e46c55bc":{
        "scriptId":"u59"},
      "d68fb64882b64a35b506d881c6f9bd34":{
        "scriptId":"u60"},
      "24b30cb7f3c8464fabf7fc7a720d9fde":{
        "scriptId":"u61"},
      "032d0f3c18724141a5b0e0b3b9bcd0f1":{
        "scriptId":"u62"}},
    "a4a8753de5e042c09c0a0fdcce6b53e8":{
      "scriptId":"u63"},
    "87eb3b659deb40308c4c754504da0b5d":{
      "scriptId":"u64"},
    "9e0ae18402384ffe916d452dbd1fd5ae":{
      "scriptId":"u65"},
    "dfa8c73c55d24a61979e18f1c1b803d9":{
      "scriptId":"u66"},
    "0d2976e8560d43eb916959d16c9e68ea":{
      "scriptId":"u67",
      "3d7e626b3ec44990ba4e13be5a550bbc":{
        "scriptId":"u68"},
      "7faabc3d868940feae97ce8b702415e0":{
        "scriptId":"u69"},
      "b9a5dd6da1774fc38a08c66f8d477197":{
        "scriptId":"u70"},
      "ee1309b659824566b1175e8f2021d911":{
        "scriptId":"u71"},
      "ec5825be9ce94b00aef0b6c4ab7d3eb2":{
        "scriptId":"u72"},
      "903c53c4055644d7b16376f47339cedc":{
        "scriptId":"u73"},
      "8733d169521e47b7b01b8298c83e77bc":{
        "scriptId":"u74"},
      "57e0cd83185a442c9bfcfd46ac6e7a17":{
        "scriptId":"u75"},
      "5e922e0a20524484a9eee585e46c55bc":{
        "scriptId":"u76"},
      "d68fb64882b64a35b506d881c6f9bd34":{
        "scriptId":"u77"},
      "24b30cb7f3c8464fabf7fc7a720d9fde":{
        "scriptId":"u78"},
      "032d0f3c18724141a5b0e0b3b9bcd0f1":{
        "scriptId":"u79"}},
    "eb2e03133e6f408280f7b730c8972231":{
      "scriptId":"u80"},
    "7fbf0f0b60644dc28b62ee757c9b1431":{
      "scriptId":"u81"},
    "cc97ad3307fe48b1ae6ba452b772971d":{
      "scriptId":"u82"},
    "4c034ff7fcdc423ebf36d8f548d9439c":{
      "scriptId":"u83"},
    "c9421bd4250245e58c4e7ac66369235f":{
      "scriptId":"u84",
      "870dc619b7624a7bb783758f3e6bcd4c":{
        "scriptId":"u85"},
      "a6e193a87c9d4f9195b6f661c0b52840":{
        "scriptId":"u86"},
      "3547c6d0057241b89e44c854c7c2eca3":{
        "scriptId":"u87"},
      "667820f597ef4e0abf8570b20c866830":{
        "scriptId":"u88"},
      "82d7356c9b724809b3af215af0dd059f":{
        "scriptId":"u89"},
      "4180d91bb6064e3f87560e5870f1dafc":{
        "scriptId":"u90"},
      "000c88dfb4b948d5bbf4cbe2e8b1909e":{
        "scriptId":"u91"},
      "760d9d7785044c1295470b90c6a958c1":{
        "scriptId":"u92"},
      "be89e24431f04a1282f2e9141f45781e":{
        "scriptId":"u93"},
      "d43eda697b704de1bc0e36c7f398d8be":{
        "scriptId":"u94"},
      "18965694c5f4461195ea9458b4d829f8":{
        "scriptId":"u95"},
      "4286e00408be47da99e534eda7881137":{
        "scriptId":"u96"},
      "d879fd40860b40298b7746dca7a6d674":{
        "scriptId":"u97"},
      "5408cd0d4a4745b08a43b49508626916":{
        "scriptId":"u98"},
      "6c6a8342a39d456e9e9991ff6c3b2c28":{
        "scriptId":"u99"},
      "1947b3844d8c4c4f8f32d19f58b1195f":{
        "scriptId":"u100"},
      "ef6d6109bc204e50bfb5b852672f4561":{
        "scriptId":"u101"},
      "2038dfac4b9947f68ee022a21392f3c2":{
        "scriptId":"u102"},
      "19c3e87af52c4e54af20881dc99afe8d":{
        "scriptId":"u103"},
      "c3c0b06791e5491a9f22fc47f76da691":{
        "scriptId":"u104"},
      "708a2a31f49e46febde87f114eadab48":{
        "scriptId":"u105"},
      "5a5d0df23a354b1ba2fb6883515a2945":{
        "scriptId":"u106"},
      "5f7a6c9306d94dc287dffad228e53e1d":{
        "scriptId":"u107"},
      "803048c9993a474495d8f229da259ae1":{
        "scriptId":"u108"},
      "6a1ccd5ff2ea476ab0083c66675a8ad0":{
        "scriptId":"u109"},
      "5cda459e85a14a02a33863959d2fc476":{
        "scriptId":"u110"},
      "b9f6be80841146cdb7e4d06fb833b0a4":{
        "scriptId":"u111"},
      "912acfaaa26a40939c9f67b9de6f4e1a":{
        "scriptId":"u112"},
      "8e0388dfda8d4ddf99579afecffe97b4":{
        "scriptId":"u113"},
      "4d65728ec7c846e085d905c737049f0e":{
        "scriptId":"u114"},
      "cfb4c458f9b2475e806c1f35dae27f3b":{
        "scriptId":"u115"},
      "79ee184e62534d3b96322c07ad04aab1":{
        "scriptId":"u116"},
      "cf932e7eeef24ae98fc448da2d1ab0ee":{
        "scriptId":"u117"}}}});