$axure.loadCurrentPage({
  "url":"用户反馈.html",
  "generationDate":new Date(1422972158156.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8c72c5879de41cf9eec9d48da20ba2a",
    "type":"Axure:Page",
    "name":"用户反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb6f38b435a841498ea28945327afebe",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb3cc1f9cc5c4979a69fe00a90f78085"},
{
          "id":"39bbd988319846039825661a0036e5e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":337,
              "y":110},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daac31e3a13d4203a07d59d58a7309e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":337,
                  "y":110},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82c3318510b14d8a9474c95c98a90ae9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":360}},
          "adaptiveStyles":{
},
          "masterId":"70ecf6840e174f1ba5ed45a740d3b1b9"},
{
          "id":"7271505fc4a14e3fac783821ab99e109",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":157},
            "size":{
              "width":500,
              "height":65}},
          "adaptiveStyles":{
}},
{
          "id":"772c2a6fbf414a508590b0855846e2a2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":245},
            "size":{
              "width":500,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d775001fcab24d248b36f2cb1f5eadae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":290},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f69e1a84a7e44f0485b3bd0e376bebab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":290},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户反馈/u62.png"}},
{
          "id":"11f660ee5e3c4b19876ad7473e0a6441",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":176},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"905abad6c831405f987c2c343e4ff468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":176},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"285e57aa29f64e92aa677821a457d7f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":242},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee981deec03e44fbbbec07da1efd4201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":242},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "bb3cc1f9cc5c4979a69fe00a90f78085":{
      "packageId":"bb3cc1f9cc5c4979a69fe00a90f78085",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd2df894b45c4e379f35e08d5b614054",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF1371AE},
              "size":{
                "width":1347,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9f668b67bcb4f3a96811e5327cc55b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF1371AE},
                  "size":{
                    "width":1347,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u258.png"}},
{
            "id":"5b742cc4596646bf99fca4537acdcb57",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":70,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b5e49fae6b6e4dfd87dfa817ba65d468",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":70,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u260.jpg"}},
{
            "id":"1fde09a019704bfcbf25ddcb7563e576",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":100,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13005ff44f374dfcbc824dbe6c171e21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":100,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 Home",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e422d49570b44cfb27df77131e605ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":170,
                "y":21},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b01253aa4f6f42ab8f1f7258f3c00ceb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":170,
                    "y":21},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 正在融资",
                        "target":{
                          "targetType":"page",
                          "url":"正在融资.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ef1b474b0b54429597e6e24231f603cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":293,
                "y":21},
              "size":{
                "width":73,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2e59a1c474944aa3e9f08dfdaa43b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":293,
                    "y":21},
                  "size":{
                    "width":73,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da23cf4ea68e4b13a1ce2efa46e0f900",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":783,
                "y":20},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fe7c027da924e5eaa58a7363af19273",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":783,
                    "y":20},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"92229a63fff24dd3ba904dbf342ff54f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":1020,
                "y":21},
              "size":{
                "width":230,
                "height":28}},
            "adaptiveStyles":{
}},
{
            "id":"ecab33d6a3f649a084534f2b6129ed59",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":913,
                "y":18},
              "size":{
                "width":97,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31eb8fa6cd18477a86ca228e4df829c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":913,
                    "y":18},
                  "size":{
                    "width":97,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a9b4273753446ae86373583f272f18f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":661,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1a4d85061764ac097787de029a2f210",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":661,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 注册页",
                        "target":{
                          "targetType":"page",
                          "url":"注册页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d759cfbc13004e33bcc1b58a394a4fa5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":720,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d44bc16a54646c38a61f88ea55c3cf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":720,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23cdc19380e14901a3d10a9160e2da50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":602,
                "y":21},
              "size":{
                "width":49,
                "height":31}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a3de6b9102ae4158937c72e33e915055",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":602,
                    "y":21},
                  "size":{
                    "width":49,
                    "height":31}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 管理",
                        "target":{
                          "targetType":"page",
                          "url":"管理.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"88fe3309936c4523972ca211b1cfa456",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1260,
                "y":21},
              "size":{
                "width":60,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e0cf294ca8c84d3daa52b26add15a772",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1260,
                    "y":21},
                  "size":{
                    "width":60,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目库",
                        "target":{
                          "targetType":"page",
                          "url":"项目库.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u279.png"}}]}},
    "70ecf6840e174f1ba5ed45a740d3b1b9":{
      "packageId":"70ecf6840e174f1ba5ed45a740d3b1b9",
      "type":"Axure:Master",
      "name":"bottom",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"870dc619b7624a7bb783758f3e6bcd4c",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":-91,
                "y":97.5},
              "size":{
                "width":1060,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u52_line.png"}},
{
            "id":"a6e193a87c9d4f9195b6f661c0b52840",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":268.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3547c6d0057241b89e44c854c7c2eca3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":268.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"667820f597ef4e0abf8570b20c866830",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":238,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d7356c9b724809b3af215af0dd059f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":238,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 隐私条款",
                        "target":{
                          "targetType":"page",
                          "url":"隐私条款.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4180d91bb6064e3f87560e5870f1dafc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":446,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"000c88dfb4b948d5bbf4cbe2e8b1909e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":446,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户反馈",
                        "target":{
                          "targetType":"page",
                          "url":"用户反馈.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"760d9d7785044c1295470b90c6a958c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":654,
                "y":290},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"be89e24431f04a1282f2e9141f45781e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":654,
                    "y":290},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d43eda697b704de1bc0e36c7f398d8be",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":134,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18965694c5f4461195ea9458b4d829f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":134,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4286e00408be47da99e534eda7881137",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":364.5,
                "y":230},
              "size":{
                "width":74,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d879fd40860b40298b7746dca7a6d674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":364.5,
                    "y":230},
                  "size":{
                    "width":74,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5408cd0d4a4745b08a43b49508626916",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":448.5,
                "y":230},
              "size":{
                "width":86,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c6a8342a39d456e9e9991ff6c3b2c28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":448.5,
                    "y":230},
                  "size":{
                    "width":86,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1947b3844d8c4c4f8f32d19f58b1195f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":534.5,
                "y":230},
              "size":{
                "width":75,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef6d6109bc204e50bfb5b852672f4561",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":534.5,
                    "y":230},
                  "size":{
                    "width":75,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2038dfac4b9947f68ee022a21392f3c2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":280,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19c3e87af52c4e54af20881dc99afe8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":280,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"c3c0b06791e5491a9f22fc47f76da691",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":364,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"708a2a31f49e46febde87f114eadab48",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":364,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5a5d0df23a354b1ba2fb6883515a2945",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":450,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f7a6c9306d94dc287dffad228e53e1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":450,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"803048c9993a474495d8f229da259ae1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":546.5,
                "y":170},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a1ccd5ff2ea476ab0083c66675a8ad0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":546.5,
                    "y":170},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u69.png"}},
{
            "id":"5cda459e85a14a02a33863959d2fc476",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":342,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9f6be80841146cdb7e4d06fb833b0a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":342,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 社区规范",
                        "target":{
                          "targetType":"page",
                          "url":"社区规范.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"912acfaaa26a40939c9f67b9de6f4e1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "location":{
                "x":550,
                "y":290},
              "size":{
                "width":94,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e0388dfda8d4ddf99579afecffe97b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "location":{
                    "x":550,
                    "y":290},
                  "size":{
                    "width":94,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 关于我们",
                        "target":{
                          "targetType":"page",
                          "url":"关于我们.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d65728ec7c846e085d905c737049f0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":344},
              "size":{
                "width":422,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfb4c458f9b2475e806c1f35dae27f3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":309,
                    "y":344},
                  "size":{
                    "width":422,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79ee184e62534d3b96322c07ad04aab1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":334,
                "y":400},
              "size":{
                "width":200,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf932e7eeef24ae98fc448da2d1ab0ee",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":334,
                    "y":400},
                  "size":{
                    "width":200,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u83.png"}}]}}},
  "objectPaths":{
    "fb6f38b435a841498ea28945327afebe":{
      "scriptId":"u0",
      "fd2df894b45c4e379f35e08d5b614054":{
        "scriptId":"u1"},
      "c9f668b67bcb4f3a96811e5327cc55b8":{
        "scriptId":"u2"},
      "5b742cc4596646bf99fca4537acdcb57":{
        "scriptId":"u3"},
      "b5e49fae6b6e4dfd87dfa817ba65d468":{
        "scriptId":"u4"},
      "1fde09a019704bfcbf25ddcb7563e576":{
        "scriptId":"u5"},
      "13005ff44f374dfcbc824dbe6c171e21":{
        "scriptId":"u6"},
      "2e422d49570b44cfb27df77131e605ec":{
        "scriptId":"u7"},
      "b01253aa4f6f42ab8f1f7258f3c00ceb":{
        "scriptId":"u8"},
      "ef1b474b0b54429597e6e24231f603cd":{
        "scriptId":"u9"},
      "cdf2e59a1c474944aa3e9f08dfdaa43b":{
        "scriptId":"u10"},
      "da23cf4ea68e4b13a1ce2efa46e0f900":{
        "scriptId":"u11"},
      "3fe7c027da924e5eaa58a7363af19273":{
        "scriptId":"u12"},
      "92229a63fff24dd3ba904dbf342ff54f":{
        "scriptId":"u13"},
      "ecab33d6a3f649a084534f2b6129ed59":{
        "scriptId":"u14"},
      "31eb8fa6cd18477a86ca228e4df829c8":{
        "scriptId":"u15"},
      "2a9b4273753446ae86373583f272f18f":{
        "scriptId":"u16"},
      "e1a4d85061764ac097787de029a2f210":{
        "scriptId":"u17"},
      "d759cfbc13004e33bcc1b58a394a4fa5":{
        "scriptId":"u18"},
      "8d44bc16a54646c38a61f88ea55c3cf3":{
        "scriptId":"u19"},
      "23cdc19380e14901a3d10a9160e2da50":{
        "scriptId":"u20"},
      "a3de6b9102ae4158937c72e33e915055":{
        "scriptId":"u21"},
      "88fe3309936c4523972ca211b1cfa456":{
        "scriptId":"u22"},
      "e0cf294ca8c84d3daa52b26add15a772":{
        "scriptId":"u23"}},
    "39bbd988319846039825661a0036e5e4":{
      "scriptId":"u24"},
    "daac31e3a13d4203a07d59d58a7309e7":{
      "scriptId":"u25"},
    "82c3318510b14d8a9474c95c98a90ae9":{
      "scriptId":"u26",
      "870dc619b7624a7bb783758f3e6bcd4c":{
        "scriptId":"u27"},
      "a6e193a87c9d4f9195b6f661c0b52840":{
        "scriptId":"u28"},
      "3547c6d0057241b89e44c854c7c2eca3":{
        "scriptId":"u29"},
      "667820f597ef4e0abf8570b20c866830":{
        "scriptId":"u30"},
      "82d7356c9b724809b3af215af0dd059f":{
        "scriptId":"u31"},
      "4180d91bb6064e3f87560e5870f1dafc":{
        "scriptId":"u32"},
      "000c88dfb4b948d5bbf4cbe2e8b1909e":{
        "scriptId":"u33"},
      "760d9d7785044c1295470b90c6a958c1":{
        "scriptId":"u34"},
      "be89e24431f04a1282f2e9141f45781e":{
        "scriptId":"u35"},
      "d43eda697b704de1bc0e36c7f398d8be":{
        "scriptId":"u36"},
      "18965694c5f4461195ea9458b4d829f8":{
        "scriptId":"u37"},
      "4286e00408be47da99e534eda7881137":{
        "scriptId":"u38"},
      "d879fd40860b40298b7746dca7a6d674":{
        "scriptId":"u39"},
      "5408cd0d4a4745b08a43b49508626916":{
        "scriptId":"u40"},
      "6c6a8342a39d456e9e9991ff6c3b2c28":{
        "scriptId":"u41"},
      "1947b3844d8c4c4f8f32d19f58b1195f":{
        "scriptId":"u42"},
      "ef6d6109bc204e50bfb5b852672f4561":{
        "scriptId":"u43"},
      "2038dfac4b9947f68ee022a21392f3c2":{
        "scriptId":"u44"},
      "19c3e87af52c4e54af20881dc99afe8d":{
        "scriptId":"u45"},
      "c3c0b06791e5491a9f22fc47f76da691":{
        "scriptId":"u46"},
      "708a2a31f49e46febde87f114eadab48":{
        "scriptId":"u47"},
      "5a5d0df23a354b1ba2fb6883515a2945":{
        "scriptId":"u48"},
      "5f7a6c9306d94dc287dffad228e53e1d":{
        "scriptId":"u49"},
      "803048c9993a474495d8f229da259ae1":{
        "scriptId":"u50"},
      "6a1ccd5ff2ea476ab0083c66675a8ad0":{
        "scriptId":"u51"},
      "5cda459e85a14a02a33863959d2fc476":{
        "scriptId":"u52"},
      "b9f6be80841146cdb7e4d06fb833b0a4":{
        "scriptId":"u53"},
      "912acfaaa26a40939c9f67b9de6f4e1a":{
        "scriptId":"u54"},
      "8e0388dfda8d4ddf99579afecffe97b4":{
        "scriptId":"u55"},
      "4d65728ec7c846e085d905c737049f0e":{
        "scriptId":"u56"},
      "cfb4c458f9b2475e806c1f35dae27f3b":{
        "scriptId":"u57"},
      "79ee184e62534d3b96322c07ad04aab1":{
        "scriptId":"u58"},
      "cf932e7eeef24ae98fc448da2d1ab0ee":{
        "scriptId":"u59"}},
    "7271505fc4a14e3fac783821ab99e109":{
      "scriptId":"u60"},
    "772c2a6fbf414a508590b0855846e2a2":{
      "scriptId":"u61"},
    "d775001fcab24d248b36f2cb1f5eadae":{
      "scriptId":"u62"},
    "f69e1a84a7e44f0485b3bd0e376bebab":{
      "scriptId":"u63"},
    "11f660ee5e3c4b19876ad7473e0a6441":{
      "scriptId":"u64"},
    "905abad6c831405f987c2c343e4ff468":{
      "scriptId":"u65"},
    "285e57aa29f64e92aa677821a457d7f8":{
      "scriptId":"u66"},
    "ee981deec03e44fbbbec07da1efd4201":{
      "scriptId":"u67"}}});